In [29]:
#import keras
import tensorflow as tf

In [2]:
from nltk.tokenize import word_tokenize

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
text = ["I am a boy", "She is a girl"]
vect = CountVectorizer(tokenizer=word_tokenize).fit(text)

In [21]:
x_train = []
y_train = []

In [22]:
tokenized_words = word_tokenize("I am a boy She is a girl")

In [23]:
for i in range(len(tokenized_words)-3):
    x_train.append(vect.transform([tokenized_words[i],tokenized_words[i+1],tokenized_words[i+2]]).toarray())
    y_train.append(vect.transform([tokenized_words[i+3]]).toarray())

In [24]:
x_train

[array([[0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0]], dtype=int64), array([[0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0]], dtype=int64), array([[1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1]], dtype=int64), array([[0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0]], dtype=int64), array([[0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0]], dtype=int64)]

In [25]:
y_train

[array([[0, 0, 1, 0, 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0, 1]], dtype=int64),
 array([[0, 0, 0, 0, 0, 1, 0]], dtype=int64),
 array([[1, 0, 0, 0, 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, 1, 0, 0, 0]], dtype=int64)]

In [30]:
X = tf.placeholder(tf.float32, [3,7]) #x_train의 각 값을 넣을 것임 
W = tf.Variable(tf.random_normal([7, 2], seed=0))
b = tf.Variable(tf.random_normal([3,2], seed=0))
expr = tf.matmul(X, W) + b

In [45]:
x_data = []
# 차원 축소 및 flatten
for i in range(5):
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    #print("=== W ===")
    #print(sess.run(W))
    #print("=== b ===")
    #print(sess.run(b))
    x_data.append(sess.run(expr, feed_dict={X: x_train[i]}).flatten())

print(x_data)

[array([-1.35984671,  1.45334113,  0.34214449,  1.09303629, -2.82256031,
        2.52699327], dtype=float32), array([-0.22808537,  2.65095735, -0.22808537,  2.65095735, -4.84680557,
        0.84510797], dtype=float32), array([-0.79831523,  4.20887852, -2.25233054,  0.9690721 , -3.72431469,
       -0.08132169], dtype=float32), array([-2.82256031,  2.52699327, -1.12983978,  0.04264247, -2.30886912,
        0.3190062 ], dtype=float32), array([-1.70006967,  1.60056353,  0.28560585,  0.44297037, -2.82256031,
        2.52699327], dtype=float32)]


In [27]:
# x_list = []
# for i in range(3):
#     for j in range(7):
#         x_list.append(x_train[0][i][j])
# x_data.append(x_list)

#np.random.random((5,7))

In [149]:
x_data = np.array(x_data)

In [153]:
x_data[1]

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [46]:
from keras.models import Model
from keras.layers import Dense, Input

Using TensorFlow backend.


In [58]:
x = Input([6,])
h = Dense(64, activation='tanh')(x)
y = Dense(7, activation='softmax')(h)

In [59]:
model = Model(x,y)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         (None, 6)                 0         
_________________________________________________________________
dense_9 (Dense)              (None, 64)                448       
_________________________________________________________________
dense_10 (Dense)             (None, 7)                 455       
Total params: 903
Trainable params: 903
Non-trainable params: 0
_________________________________________________________________


In [60]:
model.compile(loss="categorical_crossentropy", optimizer='sgd', metrics=['accuracy'])

In [64]:
import numpy as np

In [67]:
x_data = np.array(x_data).reshape(5,6)

In [70]:
y_train = np.array(y_train).reshape(5,7)

In [87]:
model.fit(x_data, y_train, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 600us/step - loss: 1.9199 - acc: 0.2000
Epoch 2/100
5/5 [==============================] - 0s 601us/step - loss: 1.8609 - acc: 0.2000
Epoch 3/100
5/5 [==============================] - 0s 600us/step - loss: 1.8063 - acc: 0.2000
Epoch 4/100
5/5 [==============================] - 0s 601us/step - loss: 1.7553 - acc: 0.2000
Epoch 5/100
5/5 [==============================] - 0s 601us/step - loss: 1.7078 - acc: 0.4000
Epoch 6/100
5/5 [==============================] - 0s 601us/step - loss: 1.6632 - acc: 0.4000
Epoch 7/100
5/5 [==============================] - 0s 600us/step - loss: 1.6213 - acc: 0.4000
Epoch 8/100
5/5 [==============================] - 0s 601us/step - loss: 1.5819 - acc: 0.4000
Epoch 9/100
5/5 [==============================] - 0s 601us/step - loss: 1.5446 - acc: 0.4000
Epoch 10/100
5/5 [==============================] - 0s 600us/step - loss: 1.5095 - acc: 0.4000
Epoch 11/100
5/5 [==============================] - 0s 600u

Epoch 88/100
5/5 [==============================] - 0s 600us/step - loss: 0.6255 - acc: 1.0000
Epoch 89/100
5/5 [==============================] - 0s 400us/step - loss: 0.6214 - acc: 1.0000
Epoch 90/100
5/5 [==============================] - 0s 400us/step - loss: 0.6174 - acc: 1.0000
Epoch 91/100
5/5 [==============================] - 0s 801us/step - loss: 0.6135 - acc: 1.0000
Epoch 92/100
5/5 [==============================] - 0s 400us/step - loss: 0.6096 - acc: 1.0000
Epoch 93/100
5/5 [==============================] - 0s 600us/step - loss: 0.6058 - acc: 1.0000
Epoch 94/100
5/5 [==============================] - 0s 600us/step - loss: 0.6021 - acc: 1.0000
Epoch 95/100
5/5 [==============================] - 0s 400us/step - loss: 0.5984 - acc: 1.0000
Epoch 96/100
5/5 [==============================] - 0s 601us/step - loss: 0.5948 - acc: 1.0000
Epoch 97/100
5/5 [==============================] - 0s 801us/step - loss: 0.5912 - acc: 1.0000
Epoch 98/100
5/5 [==============================] 

In [96]:
pre = model.predict(x_data)

In [107]:
for i in range(5):
    print(tokenized_words[i: i+3], end='===>')
    print(pre[i].argmax(), end=' ')
    print(vect.get_feature_names()[pre[i].argmax()])

['I', 'am', 'a']===>2 boy
['am', 'a', 'boy']===>6 she
['a', 'boy', 'She']===>5 is
['boy', 'She', 'is']===>0 a
['She', 'is', 'a']===>3 girl
